logging:
  level:
    it.rrredbeard: ${APP_LOG_LEVEL:info}

spring:
  profiles:
    include: 'common'

  application:
    name: ${APP_NAME:dlq-app-${random.uuid}}

  cloud:
    stream:
      bindings:
        # INPUT
        input:
          destination: ${TOPIC_IN}
          group: kcg-${spring.application.name:${random.uuid}}
          consumer:
            concurrency: ${TOPIC_PART_NO:1}
            defaultRetryable: false
            maxAttempts: 1
        # OUTPUT
        output:
          destination: ${TOPIC_OUT}
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
          headers: ${KAFKA_CUSTOM_HEADERS}
        bindings:
          input:
            consumer:
              enableDlq: false
              autoCommitOffset: true
              autoCommitOnError: true

dlq-recovery-app:
  logDurationEnabled: ${LOG_DURATION_ENABLED:false}
  logDlqExceptionEnabled: ${LOG_EXCEPTION_ENABLED:false}
  allowedHeaders: ${ALLOWED_HEADERS}
  noRetryHeader: x-no-retry-${spring.application.name}
  noRetryValue: ${spring.cloud.stream.bindings.input.group}
